#!/bin/sh
# Copyright (C) 2020 Harold Grovesteen
#
# This file is part of SATK.
#
#     SATK is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     SATK is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with SATK.  If not, see <http://www.gnu.org/licenses/>.

# NOTICES: z/Architecture is a registered trademark of International Business
# Machines Corporation.

# Assembles the booted "Hello World" program into a list-directed IPL directory
# with a listing.
#
# Run Directory: ${SATK}/samples/guide/pgm5/s390x
# Target Architecture: z/Architecture(R)
#
# This script MUST be executed from SATK's samples/guide/pgm5/s390x directory.
# Just type ./asm to rebuild the list-directed IPL directory.

datetime()
{
	sfx=$(date +%Y%m%d.%H%M%S)
}
datetime   # set $sfx (the date and time of the run) for later use

# Change this variable for your environment
REPO=${HOME}/SATKREPO/SATK           # SATK repository from github

# This variable is for the author's use.  Just leave it alone.
#REPO=${HOME}/SATKCLONE

# ASMA related script variables
ASMA=${REPO}/tools/asma.py           # The ASMA tool
LODRMACS=${REPO}/lodrmac             # Loader macros
SATKMACS=${REPO}/maclib              # General SATK macros
# ${REPO}/samples/guide/pgm5/s390x   # Guide dir being used. Output goes here.

# Assemble the program
export MACLIB=${LODRMACS}:${SATKMACS}   # Access supplied macros
${ASMA} -t s390x -d --stats -g ldipl/pgm5.txt -l asma-$sfx.txt pgm5.asm
