#!/bin/sh
# Copyright (C) 2020 Harold Grovesteen
#
# This file is part of SATK.
#
#     SATK is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     SATK is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with SATK.  If not, see <http://www.gnu.org/licenses/>.

# Assemble the XCARD test program into an object module using ASMA

# This script MUST be executed from SATK's xcard/s390 directory or your
# local directory copy.
# Just type ./asmtst in the XCARD directory or local copy.


datetime()
{
	sfx=$(date +%Y%m%d.%H%M%S)
}
datetime   # set $sfx (the date and time of the run) for later use

# Change this variable for your environment
REPO=${HOME}/SATKREPO/SATK      # SATK repository from github

# This variable is for the author's use.  Just leave it alone
#REPO=${HOME}/SATKCLONE

# ASMA related script variables
ASMA=${REPO}/tools/asma.py       # The ASMA tool
SATKMACS=${REPO}/maclib          # General SATK macros
SOURCE=${REPO}/xcard             # Source for the assembly

# Assemble the program
export ASMPATH=${SOURCE}    # XCARD test program source directory
export MACLIB=${SOURCE}:${SATKMACS}   # Access SATK macros and XCARDTST.mac
${ASMA} -t s390 -d --stats -o xcardtst.deck -l asmtst-$sfx.txt xcardtst.asm
