#!/bin/sh
# Copyright (C) 2020 Harold Grovesteen
#
# This file is part of SATK.
#
#     SATK is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     SATK is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with SATK.  If not, see <http://www.gnu.org/licenses/>.

# Execute the IPL capable emulated card deck using Hercules

# This script MUST be executed from SATK's xcard/s390 directory or your local
# copy.
# Just type ./iplc in the XCARD directory to IPL and run the XCARD test
# program from an emulated card deck.

datetime()
{
	sfx=$(date +%Y%m%d.%H%M%S)
}
datetime   # set $sfx (the date and time of the run) for later use

# Change this variable for your environment
HERCULES=${HOME}/hyperioni/bin/hercules  # Hercules location directory

export HERCULES_RC=iplc.rc
${HERCULES} -v -f iplc.conf  >> iplc-${sfx}.txt
